### ISSUE TITLE
Font awesome brands don't work.

### ISSUE THREAD

**Issue by laurent-b4y** [smillart/Framework-SASS-Source-Files#1]
Hi, 
Font awesome brands should use this font-family: "Font Awesome 5 Brands". Whitout it doesn't work.

Still loving the framework ;)

**Comment by smillart** [comment]
Hi Laurent,
I'm afraid I do not understand... The framework is designed for using Font Awesome icons but it does not provide the library itself. You have to load the Font Awesome library from your project (Kiso loads FA from the *.libraries.yml file)

**Comment by laurent-b4y** [comment]
Hi no worries, the "@include fa-icon('facebook-f', $position:'after');" doesn't work (or any other brand icon for that matter), unless you add font-family: "Font Awesome 5 Brands" to the pseudo after. I'm using this with kiso as you know, so no need to load FA a second time.

**Comment by smillart** [comment]
I understood now... Take a look at the [line 18 of the **Font Awesome's Free Icons** mixin](https://github.com/smillart/Framework-SASS-Source-Files/blob/master/mixins/typography/fontawesome/_fa-icon.scss#L18). You will see that the `fa-icon()` mixin uses 3 parameters where the second one is `$type`. By default its value is `solid` but 2 other values are allowed: `regular` and `brands`. If you explicitly set the `brands` value for the `$type` parameter, it will use the correct `font-family: 'Font Awesome 5 Brands';`. 

**SCSS usage:**
```scss
.element {
  @include fa-icon('facebook-f', $type: 'brands', $position: 'after');
}
```

**CSS output:**
```css
.element::after {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  display: inline-block;
  font-style: normal;
  font-variant: normal;
  text-rendering: auto;
  line-height: 1;
}
.element::after {
  font-family: 'Font Awesome 5 Brands';
}
.element::after {
  content: '\f39e';
}
```
